# Lab 02: Manipulate PyTorch Tensors -- solution

In [1]:
import torch

### Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad 
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [2]:
A=torch.Tensor( [ [1,2] , [3,4] ] )
B=torch.Tensor( [ [10,20] , [30,40] ] )

C=A+B

print(A)
print('')
print(B)
print('')
print(C)

tensor([[1., 2.],
        [3., 4.]])

tensor([[10., 20.],
        [30., 40.]])

tensor([[11., 22.],
        [33., 44.]])


### Print the sizes, dimension, and type of the matrix A. Remember, the commands are size(), dim() and type()

In [3]:
print( A.size() )
print( A.dim() )
print( A.type() )

torch.Size([2, 2])
2
torch.FloatTensor


### Convert the matrix A to be an integer matrix  (type LongTensor). Remember, the command is long(). Then print the type to check it was indeed converted.

In [4]:
A=A.long()
print(A)
print(A.type())

tensor([[1, 2],
        [3, 4]])
torch.LongTensor


### Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following:   1) Print the tensor,  2) Print its type, 3) Print its dimension,  4) Print its size, 5) Print the size of its middle dimension.

In [5]:
A=torch.rand(5,2,3)
print(A)
print(A.type())
print(A.dim())
print(A.size())
print(A.size(1))

tensor([[[0.5488, 0.3518, 0.4647],
         [0.9966, 0.4741, 0.5914]],

        [[0.2228, 0.1298, 0.2617],
         [0.5139, 0.3943, 0.5260]],

        [[0.8017, 0.2486, 0.5686],
         [0.2437, 0.4197, 0.6545]],

        [[0.6615, 0.6826, 0.3762],
         [0.6373, 0.3283, 0.7173]],

        [[0.5708, 0.2817, 0.0934],
         [0.9079, 0.1496, 0.4506]]])
torch.FloatTensor
3
torch.Size([5, 2, 3])
2


### Make 2 x 3 x 4 x 5 tensor filled with zeros then print it. (The command is torch.zeros). See if you can make sense of the display.

In [6]:
A=torch.zeros(2,3,4,5)
print(A)

tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])
