# Lab 01 : Linear module -- demo

In [1]:
import torch
import torch.nn as nn

### Make a _Linear Module_ that takes input of size 5 and return output of size 3

In [2]:
mod = nn.Linear(5,3)
print(mod)

Linear(in_features=5, out_features=3, bias=True)


### Let's make a random tensor of size 5:

In [3]:
x=torch.rand(5)
print(x)
print(x.size())

tensor([0.0119, 0.1450, 0.3117, 0.2817, 0.0672])
torch.Size([5])


### Feed it to the module:

In [4]:
y=mod(x)
print(y)

tensor([ 0.1172, -0.4226, -0.2997], grad_fn=<ViewBackward0>)


### The output y is computed according to the formula:
$$
\begin{bmatrix}
y_1\\ y_2 \\y_3 
\end{bmatrix} =
\begin{bmatrix}
w_{11} & w_{12} & w_{13}& w_{14}& w_{15} \\
w_{21} & w_{22} & w_{23}& w_{24}& w_{25} \\
w_{31} & w_{32} & w_{33}& w_{34}& w_{35} \\
\end{bmatrix}
\begin{bmatrix}
x_1\\ x_2 \\x_3 \\ x_4 \\x_5
\end{bmatrix}
+
\begin{bmatrix}
b_1\\ b_2 \\b_3 
\end{bmatrix}
$$
### were the $w_{ij}$'s are the weight parameters and the $b_i$'s are the bias parameters. These internal parameters can be access as follow:

In [5]:
print(mod.weight)
print(mod.weight.size())

Parameter containing:
tensor([[-0.1595,  0.0223, -0.4264,  0.0868, -0.2780],
        [ 0.3804, -0.2547, -0.0609, -0.1142,  0.0675],
        [ 0.1946, -0.1961, -0.4225, -0.0934, -0.3861]], requires_grad=True)
torch.Size([3, 5])


In [6]:
print(mod.bias)
print(mod.bias.size())

Parameter containing:
tensor([ 0.2430, -0.3437, -0.0896], requires_grad=True)
torch.Size([3])


### If we want we can change the internal parameters of the module:

In [7]:
with torch.no_grad():
    mod.weight[0,0]=0
    mod.weight[0,1]=1
    mod.weight[0,2]=2
    print(mod.weight)

Parameter containing:
tensor([[ 0.0000,  1.0000,  2.0000,  0.0868, -0.2780],
        [ 0.3804, -0.2547, -0.0609, -0.1142,  0.0675],
        [ 0.1946, -0.1961, -0.4225, -0.0934, -0.3861]], requires_grad=True)


### We can also make a Linear module without bias:

In [8]:
mod2 = nn.Linear(5,3,bias=False)
print(mod2)

Linear(in_features=5, out_features=3, bias=False)


In [9]:
print(mod2.weight)

Parameter containing:
tensor([[-0.2536, -0.3423, -0.3418, -0.0972,  0.2690],
        [ 0.1647,  0.0055, -0.2789,  0.1286,  0.4333],
        [-0.3599, -0.4434,  0.3164,  0.4091, -0.0479]], requires_grad=True)


In [10]:
print(mod2.bias)

None
