# Lab 01 : Convolutional layer - demo

In [1]:
import torch
import torch.nn as nn

### Make a convolutional module
* inputs:  2 channels
* output:  5 activation maps 
* filters are 3x3
* padding with one layer of zero to not shrink anything

In [2]:
mod = nn.Conv2d( 2 , 5 ,  kernel_size=3,  padding=1 )

### Make an input 2 x 6 x 6  (two channels, each one has 6 x 6 pixels )

In [3]:
bs=1

x=torch.rand(bs,2,6,6)

print(x)

print(x.size())

tensor([[[[0.2300, 0.7781, 0.1270, 0.6165, 0.2159, 0.2305],
          [0.7977, 0.7647, 0.3813, 0.9563, 0.2737, 0.2726],
          [0.7713, 0.6809, 0.8082, 0.3983, 0.0445, 0.2156],
          [0.5649, 0.7692, 0.4926, 0.2446, 0.0496, 0.4686],
          [0.7863, 0.4914, 0.1137, 0.5299, 0.0566, 0.1930],
          [0.7637, 0.9185, 0.1417, 0.3711, 0.8981, 0.4315]],

         [[0.3151, 0.1544, 0.7182, 0.5631, 0.6663, 0.0329],
          [0.7042, 0.1636, 0.5210, 0.5416, 0.0216, 0.3069],
          [0.6235, 0.1845, 0.2730, 0.2023, 0.6104, 0.8568],
          [0.5230, 0.1634, 0.7620, 0.4651, 0.2810, 0.1646],
          [0.7083, 0.0480, 0.4354, 0.6570, 0.3878, 0.9161],
          [0.6405, 0.4511, 0.0844, 0.9408, 0.9243, 0.7954]]]])
torch.Size([1, 2, 6, 6])


### Feed it to the convolutional layer: the output should have 5 channels (each one is 6x6)

In [4]:
y=mod(x)

print(y)

print(y.size())

tensor([[[[ 0.2905,  0.2507,  0.3145,  0.2159,  0.2577,  0.2617],
          [ 0.3205,  0.1495,  0.3122,  0.1692,  0.2389,  0.1920],
          [ 0.2481,  0.1027,  0.3630,  0.0846,  0.1390,  0.1005],
          [ 0.2093,  0.1746,  0.1746,  0.0187,  0.0609,  0.2718],
          [ 0.2422,  0.0876,  0.1214,  0.1810,  0.0240,  0.1578],
          [ 0.2160,  0.2281,  0.1573,  0.1019,  0.1765,  0.2150]],

         [[ 0.2304,  0.4922,  0.2240,  0.5486,  0.2182,  0.3612],
          [ 0.1227,  0.2369,  0.0011,  0.3703,  0.3023,  0.2718],
          [-0.1395,  0.2953, -0.0264,  0.0927,  0.0924,  0.2378],
          [-0.0905,  0.1800,  0.0562,  0.3467,  0.0714,  0.1945],
          [ 0.0085,  0.2176, -0.1301,  0.3982,  0.4521, -0.0104],
          [-0.0203,  0.5005,  0.2784,  0.2458,  0.6541,  0.4301]],

         [[ 0.2106,  0.3130,  0.5039,  0.2966,  0.4705,  0.1585],
          [ 0.3684,  0.5126,  0.5405,  0.4590,  0.4149, -0.0579],
          [ 0.4582,  0.5551,  0.4291,  0.3469,  0.0417,  0.2164],
      

### Lets look at the 5 filters.
* Our filters are 2x3x3
* Each of the filter has 2 channels because the inputs have two channels

In [5]:
print(mod.weight)

print(mod.weight.size())

Parameter containing:
tensor([[[[ 0.0497, -0.1770,  0.0285],
          [ 0.0219,  0.1640,  0.0509],
          [ 0.1528, -0.0771,  0.0899]],

         [[-0.0065,  0.0365, -0.1184],
          [-0.0411, -0.0587, -0.0514],
          [-0.1027,  0.0656, -0.1436]]],


        [[[-0.1778, -0.2259, -0.2055],
          [ 0.1492,  0.2328, -0.0727],
          [-0.2101,  0.1956, -0.2087]],

         [[ 0.2044, -0.2016,  0.0126],
          [ 0.1510,  0.0293,  0.1749],
          [-0.1271, -0.0362,  0.2101]]],


        [[[-0.0294,  0.1060,  0.0184],
          [ 0.1912,  0.1320,  0.2067],
          [ 0.2008,  0.0712,  0.0970]],

         [[-0.0505,  0.1570, -0.2180],
          [ 0.1778,  0.0914, -0.0622],
          [-0.0756, -0.0698,  0.0260]]],


        [[[-0.1785, -0.1977,  0.0154],
          [-0.1375, -0.0746,  0.0943],
          [ 0.0493, -0.1703, -0.0791]],

         [[-0.0987,  0.0241,  0.1511],
          [-0.1071, -0.0722, -0.1819],
          [-0.2123,  0.0783,  0.0569]]],


        [[[ 0.0904