# Lab 01: Introduction to PyTorch  

Goal: This notebook serves as a foundational introduction to PyTorch Tensors, providing the essential knowledge required to create and manipulate the primary data structures used in deep learning.

Implement: It demonstrates how to construct tensors of various dimensions, perform arithmetic operations, and manage data types such as Floats and Longs. Furthermore, it covers practical techniques for reshaping data with .view(), slicing tensors to extract subsets, and converting scalar tensor entries into standard Python numbers using .item().

In [1]:
import torch

### PyTorch Tensors

### Construct a vector of 3 elements

In [2]:
x=torch.Tensor( [5.3 , 2.1 , -3.1 ] )
print(x)

tensor([ 5.3000,  2.1000, -3.1000])


### Construct a  2 x 2 matrix

In [3]:
A=torch.Tensor( [ [5.3,2.1] , [0.2,2.1] ] )
print(A)

tensor([[5.3000, 2.1000],
        [0.2000, 2.1000]])


### Construct a random 10 x 2 matrix

In [4]:
A=torch.rand(10,2)
print(A)

tensor([[0.8114, 0.8184],
        [0.4162, 0.4372],
        [0.4825, 0.6004],
        [0.2160, 0.0072],
        [0.6542, 0.3418],
        [0.7814, 0.8233],
        [0.6724, 0.5450],
        [0.5812, 0.6544],
        [0.4956, 0.3963],
        [0.7860, 0.1109]])


### Construct a 10 x 2 matrix filled with zeros

In [5]:
A=torch.zeros(10,2)
print(A)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


### Construct a 5 x 2 x 2 random Tensor 

In [6]:
B = torch.rand(5,2,2)
print(B)

tensor([[[0.3511, 0.1443],
         [0.2434, 0.5931]],

        [[0.0249, 0.3046],
         [0.4837, 0.6981]],

        [[0.5161, 0.0959],
         [0.6826, 0.4636]],

        [[0.5371, 0.1622],
         [0.4835, 0.3666]],

        [[0.7696, 0.9262],
         [0.8268, 0.7201]]])


In [7]:
B.size()

torch.Size([5, 2, 2])

In [8]:
B.dim()

3

In [9]:
B.type()

'torch.FloatTensor'

### Size and Dimension of a Tensor 

#### A 3-dimensional Tensor 

In [10]:
A=torch.rand(3,2,2)
print(A)

tensor([[[0.6273, 0.1054],
         [0.8588, 0.8965]],

        [[0.6881, 0.2835],
         [0.7619, 0.5098]],

        [[0.3550, 0.2105],
         [0.4907, 0.5194]]])


In [11]:
print(  A.dim()   )

3


In [12]:
print(  A.size()   )

torch.Size([3, 2, 2])


In [13]:
print(  A.size(0)  )

3


#### A 2-dimensional Tensor 

In [14]:
B=torch.rand(3,5)
print(B)

tensor([[0.6606, 0.9525, 0.2403, 0.0572, 0.3325],
        [0.1965, 0.2891, 0.0443, 0.6781, 0.4574],
        [0.7205, 0.5055, 0.8827, 0.2862, 0.2415]])


In [15]:
print( B.dim()  )

2


In [16]:
print( B.size()  )

torch.Size([3, 5])


In [17]:
print( B.size(0) )

3


In [18]:
print( B.size(1) )

5


#### A 1-dimensional Tensor

In [19]:
x=torch.rand(7)
print(x)

tensor([0.0333, 0.1836, 0.6717, 0.8516, 0.3092, 0.8304, 0.4762])


In [20]:
print( x.dim() )

1


In [21]:
print( x.size() )

torch.Size([7])


### Adding and multiplying tensors

In [22]:
A=torch.rand(2,2)
B=torch.rand(2,2)

C=2*B
D=A+C
E=A*B

print(A)
print('')
print(B)
print('')
print(C)
print('')
print(C)
print('')
print(E)

tensor([[0.8931, 0.0541],
        [0.5739, 0.3661]])

tensor([[0.3022, 0.6001],
        [0.5199, 0.5160]])

tensor([[0.6043, 1.2002],
        [1.0398, 1.0320]])

tensor([[0.6043, 1.2002],
        [1.0398, 1.0320]])

tensor([[0.2699, 0.0325],
        [0.2984, 0.1889]])


### Floats versus integers

In [23]:
x=torch.Tensor([1.2 , 2.5])
print(x)
print(x.type())

tensor([1.2000, 2.5000])
torch.FloatTensor


In [24]:
y=torch.LongTensor([5,6])
print(y)
print(y.type())

tensor([5, 6])
torch.LongTensor


In [25]:
y=y.float()
print(y)
print(y.type())

tensor([5., 6.])
torch.FloatTensor


In [26]:
x=x.long()
print(x)
print(x.type())

tensor([1, 2])
torch.LongTensor


### Other functions

In [27]:
x=torch.arange(10)
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


In [28]:
x=torch.randperm(10)
print(x)
print(x.type())

tensor([1, 9, 7, 8, 6, 2, 4, 0, 3, 5])
torch.LongTensor


In [29]:
x=torch.arange(10).long()
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


### Tips

Check tensor sizes for algebra computations like multiplication torch.mm(X1,X2) with X1.size(), X2.size()

Check tensor type for data manipulations with X.type()

### Reshaping a tensor

In [30]:
x=torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [31]:
print( x.view(2,5) )

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [32]:
print( x.view(5,2) )

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


### Note that the original tensor x was NOT modified

In [33]:
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### To make the change permanent you need to create a new tensor

In [34]:
y=x.view(5,2)

print(x)
print('')
print(y)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


### Slicing a tensor

In [35]:
print( y )

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [36]:
print( y[0] )

tensor([0, 1])


In [37]:
print( y[1] )

tensor([2, 3])


In [38]:
v = y[2]
print(v)

tensor([4, 5])


### Extract row 1 (included) to row 4 (excluded)

In [39]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [40]:
print( y[1:4] )

tensor([[2, 3],
        [4, 5],
        [6, 7]])


In [41]:
idx = 1
n=3

print( y[idx:idx+n] )

tensor([[2, 3],
        [4, 5],
        [6, 7]])


### Let check the sizes after slicing

In [42]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [43]:
z= y[1:1+3]
print(z)

print('')

print('dimension=',z.dim())
print(z.size())

tensor([[2, 3],
        [4, 5],
        [6, 7]])

dimension= 2
torch.Size([3, 2])


In [44]:
v=y[1]
print(v)

print('')


print('dimension=',v.dim())
print(v.size())

tensor([2, 3])

dimension= 1
torch.Size([2])


### Acessing the entries of a Tensor

In [45]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [46]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [47]:
a=y[4,0]
print(a) # a is a scalar, not a tensor

tensor(8)


In [48]:
print(a.dim())
print(a.size())

0
torch.Size([])


### A matrix is 2-dimensional Tensor
### A row of a matrix is a 1-dimensional Tensor
### An entry of a matrix is a 0-dimensional  Tensor

### 0-dimensional Tensor are scalar!

### If we want to convert a 0-dimensional Tensor into  python number, we need to use item()

In [49]:
b=a.item()
print(a)
print(type(a))
print(b)
print(type(b))

tensor(8)
<class 'torch.Tensor'>
8
<class 'int'>
